from src.og_agents.prompts.generate_competency_questions_prompt import GenerateCompetencyQuestionsPrompt
from src.og_agents.prompts.generate_ontology_prompt import GenerateOntologyPrompt

__all__ = ["GenerateCompetencyQuestionsPrompt", "GenerateOntologyPrompt"]